name: Check pubring file

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  lint-pubring:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Re-generate gpg folder
        run: |
          rm -rf "GNUPGHOME"
          mkdir "GNUPGHOME"
          gpg --import keys/*
        env:
          GNUPGHOME: ${{ github.workspace }}/gpg
      - run: git diff --exit-code -- gpg
