name: Check pubring file

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  lint-pubring:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Export pubring content
        run: |
          gpg --no-default-keyring --keyring "gpg/pubring.kbx" --list-keys --with-colons > all-keys.list
          gpg --no-default-keyring --keyring "gpg/pubring.kbx" --export --armor > all-keys.asc
          gpg --no-default-keyring --keyring "gpg-only-active-keys/pubring.kbx" --list-keys --with-colons > active-keys.list
          gpg --no-default-keyring --keyring "gpg-only-active-keys/pubring.kbx" --export --armor > active-keys.asc
          git add all-keys.list all-keys.asc active-keys.list active-keys.asc
      - name: Re-generate gpg folder
        run: |
          ./generate-gpg-dir.sh
          gpg --no-default-keyring --keyring "gpg/pubring.kbx" --list-keys --with-colons > all-keys.list
          gpg --no-default-keyring --keyring "gpg/pubring.kbx" --export --armor > all-keys.asc
          gpg --no-default-keyring --keyring "gpg-only-active-keys/pubring.kbx" --list-keys --with-colons > active-keys.list
          gpg --no-default-keyring --keyring "gpg-only-active-keys/pubring.kbx" --export --armor > active-keys.asc
      - run: git diff --exit-code -- all-keys.list all-keys.asc active-keys.list active-keys.asc
